POST https://api.telegram.org/bot5706618703:AAGcJ_1iGj6c-CXrJ-ik_QNUpzbIb6S79t4/getWebhookInfo
###
POST https://api.telegram.org/bot5706618703:AAGcJ_1iGj6c-CXrJ-ik_QNUpzbIb6S79t4/setWebhook?url=https://10f5-37-212-80-154.eu.ngrok.io
###
POST https://api.telegram.org/bot5706618703:AAGcJ_1iGj6c-CXrJ-ik_QNUpzbIb6S79t4/sendMessage?chat_id=621620935&text=Hello, it's me
###
POST https://api.telegram.org/bot5706618703:AAGcJ_1iGj6c-CXrJ-ik_QNUpzbIb6S79t4/deleteMessage?chat_id=621620935&message_id=491
###
POST https://api.telegram.org/bot5706618703:AAGcJ_1iGj6c-CXrJ-ik_QNUpzbIb6S79t4/sendMessage?chat_id=621620935&text=/start