package com.godeltech.gbf.gui.button;

public enum FormButton implements BotButton {
    ADD_INITIAL_ROUTE_POINT, EDIT_INITIAL_ROUTE_POINT,
    ADD_FINAL_ROUTE_POINT, EDIT_FINAL_ROUTE_POINT,
    ADD_INTERMEDIATE_ROUTE_POINT,
    INTERMEDIATE_EDITOR,
    ADD_COMMENT, EDIT_COMMENT, DELETE_COMMENT,
    ADD_CARGO, EDIT_CARGO,
    FORM_REGISTER, FORM_SEARCH
}
