package com.godeltech.gbf.model;

public enum BotState {
    MAIN_MENU, REGISTRATIONS, COUNTRY_FROM, CITY_FROM, YEAR_FROM, MONTH_FROM, DAY_FROM,
    COUNTRY_TO, CITY_TO, YEAR_TO, MONTH_TO, DAY_TO, CARGO, HELP, FINISH, BACK
}
