package com.godeltech.gbf.model;

import lombok.Getter;

@Getter
public enum State {
    FORM, ROUTE_POINT_FORM, INTERMEDIATE_EDITOR,
    MENU, SUCCESS, WRONG_INPUT,
    COMMENT,
    COUNTRY, CITY,
    YEAR, MONTH, DATE,
    CARGO_MENU, CARGO_PACKAGE, CARGO_PEOPLE,
    REGISTRATIONS, REQUESTS,
    FOUND_COURIERS_INFO, COURIERS_LIST_RESULT, CLIENTS_LIST_RESULT
}
