package com.godeltech.gbf.model;

import lombok.Getter;

@Getter
public enum State {
    FORM, ROUTE_POINT_FORM, INTERMEDIATE_EDITOR,
    MENU, SUCCESS, WRONG_INPUT, SUMMARY_DATA_TO_CONFIRM,
    COMMENT_QUIZ, COMMENT, COMMENT_CONFIRM,
    COUNTRY, CITY,
    YEAR, MONTH, DATE,
    CARGO_MENU, CARGO_PACKAGE, CARGO_PEOPLE,
    REGISTRATIONS, REGISTRATION_EDITOR,
    FOUND_COURIERS_INFO, COURIERS_LIST_RESULT, CLIENTS_LIST_RESULT,
    REQUESTS, REQUEST_EDITOR
}
